### ISSUE TITLE
Can this be used in a nodejs environment? I keep encountering  Reference error: window is not defined

### ISSUE THREAD

**Issue by tirth0** [sentinel-hub/sentinelhub-js#140] opened 2020-09-30 19:00 UTC
(node:2528) UnhandledPromiseRejectionWarning: ReferenceError: window is not defined
    at C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:289:9
    at Generator.next (<anonymous>)
    at C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:117:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:113:12)
    at checkIfCacheApiAvailable (C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:288:12)
    at C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:308:30
    at Generator.next (<anonymous>)
    at C:\Users\tirth\Desktop\New folder (3)\node_modules\@sentinel-hub\sentinelhub-js\dist\sentinelHub.cjs.js:117:71
    at new Promise (<anonymous>)
(node:2528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either 
by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2528) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.     
(node:2528) UnhandledPromiseRejectionWarning: Error: Request failed with status code 400
    at createError (C:\Users\tirth\Desktop\New folder (3)\node_modules\axios\lib\core\createError.js:16:15)
    at settle (C:\Users\tirth\Desktop\New folder (3)\node_modules\axios\lib\core\settle.js:18:12)       
    at IncomingMessage.handleStreamEnd (C:\Users\tirth\Desktop\New folder (3)\node_modules\axios\lib\adapters\http.js:202:11)
    at IncomingMessage.emit (events.js:215:7)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2528) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either 
by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)

**Comment by zcernigoj** [comment] 2020-09-30 19:50
Hey,
our goal is that the library can be used in nodejs environment or in the browser, so it should work in both. If something doesn't work, it's most probably a bug.

Can you maybe provide some more information about when the error happens? It will help us narrow down the possibilities and find the possible problematic piece quicker.

 Thanks for reporting. We will take a look and prepare a fix as soon as possible.

**Comment by sinergise-anze** [comment] 2020-10-01 05:27
Looks like the bug occurs when running a provided node.js example, and your MR (#141) fixes it nicely. We should add this to automated tests though, to avoid regressions.

@tirth0 The fix should be merged and deployed today, thank you for reporting!

**Closed** 2020-10-01 06:30 UTC

**Comment by zcernigoj** [comment] 2020-10-01 06:39
After responding I was checking a bit and prepared the merge request with the fixes of the most obvious things. The issue was closed automatically when merging the MR. The new release was deployed a few minutes ago.

If some error still pops up, don't hesitate to reopen this issue. And again thanks for reporting!

**Comment by tirth0** [comment] 2020-10-01 07:27
Thanks!
